# Generated by Django 4.2.1 on 2023-09-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_userprofilemodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='account_balance',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
